# Duplicate this file into ./config.yaml

database:
  db_path: /home/main/database.sqlite
  db_type: sqlite3
  

updaters:
  coingecko:
    enable: true

  coinmarketcap:
    enable: true

search:
  max_query_results: 49


currencies:
  usd:
    description: US Dollars
    display: USD
    prefix: $
    suffix: ''
  eur:
    description: Euros
    display: EUR
    prefix: ''
    suffix: ' EUR'
  jpy:
    description: Japanese Yen
    display: JPY
    prefix: ''
    suffix: ' JPY'
  cad:
    description: Canadian Dollars
    display: CAD
    prefix: 'CAD $'
    suffix: ''
    