# Duplicate this file into ./config.yaml

database:
  db_path: /home/main/database.sqlite
  db_type: sqlite3
  

updaters:
  coingecko:
    enable: true
    run_period_minutes: 15

  coinmarketcap:
    enable: true
    run_period_minutes: 15


search:
  max_query_results: 49
  disable_search_page: true # force redirect to CoinGecko instead of showing results pages


currencies:
  usd:
    description: US Dollars
    display: USD
    prefix: $
    suffix: ''
  eur:
    description: Euros
    display: EUR
    prefix: ''
    suffix: ' EUR'
  jpy:
    description: Japanese Yen
    display: JPY
    prefix: ''
    suffix: ' JPY'
  cad:
    description: Canadian Dollars
    display: CAD
    prefix: 'CAD $'
    suffix: ''

    
site:
  tor_hidden_service_hostname: n5rx5q7sgrghl4ks6isuu7fbslivaf66ni7nm5non53zcr5j7n4lnyid.onion

